In [1]:
import numpy as np

In [2]:
sample_arr = np.array([[0, 0, 0, 0, 0, 0, 1, 0],
                       [0, 0, 0, 0, 0, 1, 0, 0],
                       [0, 0, 0, 0, 0, 1, 0, 0],
                       [0, 0, 0, 0, 0, 1, 0, 0],
                       [0, 1, 1, 0, 0, 0, 1, 0],
                       [0, 1, 0, 0, 0, 0, 0, 1],
                       [0, 1, 0, 0, 0, 0, 0, 0],
                       [0, 1, 0, 0, 0, 0, 0, 0]])

In [3]:
ans = np.array([[5, 4, 4, 3, 2, 1, 0, 1],
                [4, 3, 3, 2, 1, 0, 1, 2],
                [3, 2, 2, 2, 1, 0, 1, 2],
                [2, 1, 1, 2, 1, 0, 1, 2],
                [1, 0, 0, 1, 2, 1, 0, 1],
                [1, 0, 1, 2, 3, 2, 1, 0],
                [1, 0, 1, 2, 3, 3, 2, 1],
                [1, 0, 1, 2, 3, 4, 3, 2]])

In [4]:
sample_arr

array([[0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0],
       [0, 1, 1, 0, 0, 0, 1, 0],
       [0, 1, 0, 0, 0, 0, 0, 1],
       [0, 1, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0]])

In [5]:
F = np.zeros((8, 8)) + 7
for i in range(8):
    for j in range(8):
        if sample_arr[i, j] == 1:
            F[i, j] = 0

In [6]:
F

array([[ 7.,  7.,  7.,  7.,  7.,  7.,  0.,  7.],
       [ 7.,  7.,  7.,  7.,  7.,  0.,  7.,  7.],
       [ 7.,  7.,  7.,  7.,  7.,  0.,  7.,  7.],
       [ 7.,  7.,  7.,  7.,  7.,  0.,  7.,  7.],
       [ 7.,  0.,  0.,  7.,  7.,  7.,  0.,  7.],
       [ 7.,  0.,  7.,  7.,  7.,  7.,  7.,  0.],
       [ 7.,  0.,  7.,  7.,  7.,  7.,  7.,  7.],
       [ 7.,  0.,  7.,  7.,  7.,  7.,  7.,  7.]])

In [7]:
def top_down_iter(arr):
    F = arr.copy()
    dim_i, dim_j = F.shape
    for i in range(dim_i):
        for j in range(dim_j):
            if i == 0 and j == 0:
                pass
            elif i == 0:
                F[i, j] = min(F[i, j], 1 + F[i, j - 1], 2 + F[i + 1, j - 1])
            elif j == 0:
                F[i, j] = min(F[i, j], F[i - 1, j] + 1)
            elif i == dim_i - 1:
                F[i, j] = min(F[i, j], 1 + F[i, j - 1], 1 + F[i - 1, j], 2 + F[i-1, j-1])
            else:
                F[i, j] = min(F[i, j], 1 + F[i, j - 1], 1 + F[i - 1, j], 2 + F[i - 1, j - 1], 2 + F[i + 1, j - 1])
    return F

In [10]:
top_down_iter(F)

array([[ 7.,  7.,  7.,  7.,  7.,  7.,  0.,  1.],
       [ 7.,  7.,  7.,  7.,  7.,  0.,  1.,  2.],
       [ 7.,  7.,  7.,  7.,  7.,  0.,  1.,  2.],
       [ 7.,  7.,  2.,  2.,  3.,  0.,  1.,  2.],
       [ 7.,  0.,  0.,  1.,  2.,  1.,  0.,  1.],
       [ 7.,  0.,  1.,  2.,  3.,  2.,  1.,  0.],
       [ 7.,  0.,  1.,  2.,  3.,  3.,  2.,  1.],
       [ 7.,  0.,  1.,  2.,  3.,  4.,  3.,  2.]])

In [9]:
def buttom_up_iter(arr):
    F = arr.copy()
    dim_i, dim_j = F.shape
    for i in range(dim_i -1, -1, -1):
        for j in range(dim_j - 1, -1, -1):
            if j == dim_j - 1 and i == dim_i - 1:
                pass
            elif i == dim_i - 1:
                F[i, j] = min(F[i, j], 1 + F[i, j + 1], 2 + F[i - 1, j + 1])
            elif j == dim_j - 1:
                F[i, j] = min(F[i, j], 1 + F[i + 1, j], 2 + F[i + 1, j - 1])
            elif i == 0:
                F[i, j] = min(F[i, j], 1 + F[i, j + 1], 1 + F[i+1, j], 2 + F[i + 1, j + 1])
            else:
                F[i, j] = min(F[i, j], 1 + F[i, j + 1], 1 + F[i + 1, j], 2 + F[i + 1, j + 1], 2 + F[i - 1, j + 1])
    return F

In [11]:
buttom_up_iter(F)

array([[ 5.,  4.,  4.,  3.,  2.,  1.,  0.,  5.],
       [ 4.,  3.,  3.,  2.,  1.,  0.,  3.,  4.],
       [ 3.,  2.,  2.,  2.,  1.,  0.,  2.,  3.],
       [ 2.,  1.,  1.,  2.,  1.,  0.,  1.,  2.],
       [ 1.,  0.,  0.,  3.,  2.,  1.,  0.,  1.],
       [ 1.,  0.,  5.,  4.,  3.,  2.,  1.,  0.],
       [ 1.,  0.,  6.,  5.,  4.,  3.,  2.,  7.],
       [ 1.,  0.,  7.,  7.,  7.,  7.,  7.,  7.]])

In [12]:
def dist_transform(arr):
    F = arr.copy()
    while 7 in F:
        F = top_down_iter(F)
        F = buttom_up_iter(F)
    return F

In [16]:
%time mapped = dist_transform(F)

CPU times: user 787 µs, sys: 230 µs, total: 1.02 ms
Wall time: 826 µs


In [17]:
np.all(mapped == ans)

True